on:
  workflow_dispatch:
  push:
    paths:
      - '**.js'
      - '**.mjs'
      - '**.cjs'
      - '**.jsx'
      - '**.ts'
      - '**.mts'
      - '**.cts'
      - '**.tsx'
      - '**.vue'
      - '**.json'
  pull_request:
    paths:
      - '**.js'
      - '**.mjs'
      - '**.cjs'
      - '**.jsx'
      - '**.ts'
      - '**.mts'
      - '**.cts'
      - '**.tsx'
      - '**.vue'
      - '**.json'

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          run_install: false

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: pnpm run lint --if-present

  # This job just check code style for in-template contributions.
  code-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          run_install: false

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: pnpm exec prettier --check "**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx,vue,json}"
